### ISSUE TITLE
Add anaconda package

### ISSUE THREAD

**Issue by natct10** [Substra/substra#130]
It would be awesome to have the substra python package also available on [anaconda](https://anaconda.org) & ready to be installed with `conda install substra`.
For now, it is returning a sad `PackagesNotFoundError`. 
What do you think about this?

**Comment by samlesu** [comment]
That would be a good idea. @natct10 would you like to propose a request?

**Comment by natct10** [comment]
> That would be a good idea. @natct10 would you like to propose a request?

Sure, I will look into this!

**Comment by RomainGoussault** [comment]
Closing as inactive. As a workaround it is possible to do a `pip install substra` inside a conda env.
