### ISSUE TITLE
Can the Substra be used for Unsupervised Machine Learning?

### ISSUE THREAD

**Issue by bdqnghi** [Substra/substra#157]
I read in the paper the see that Substra only mentioned about Supervised Machine Learning? How about the Unsupervised Machine Learning? Is Unsupervised Machine Learning applicable in Substra?

**Comment by camillemarini** [comment]
Hello @bdqnghi , sorry for the late answer and thanks for your questions! 
It would be possible to use Substra for unsupervised learning, but you would need to bend some definitions, in particular around the `data opener` and the `metrics`. 
It is planned to generalise the framework to more generic tasks in the next 6 months. 
Out of curiosity, what would be your application ?
Would you be interested in participating to this new feature and what would be your timeframe ?

**Comment by bdqnghi** [comment]
@camillemarini , thanks for the answer. My plan is to implement sth similar to Latent Dirichlet Allocation, a method to extract topics from text corpora, which is an unsupervised learning technique.
Would it be possible to do so with the current Substra framework?

**Comment by RomainGoussault** [comment]
Hello @bdqnghi it is still not possible to do unsupervised learning with the current Substra. We still plan to add this feature at some point but we are not there yet.

**Comment by Esadruhn** [comment]
Closing this issue as it is stale
