### ISSUE TITLE
Service Unavailable for url during Substra login

### ISSUE THREAD

**Issue by IcyLiGit** [Substra/substra#209]
Hi, everyone. I tried the docker installation in my ubuntu. Everything seems fine. 
However, when I logged in the backend. Errors occurred: 

```
substra config --profile owkin http://substra-backend.owkin.xyz:8000                                         
substra login --profile owkin --username substra --password 'p@$swr0d44'                                                                    
Error: Request failed: ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

Then I setup my VPN proxy and retried: 
`substra login --profile owkin --username substra --password 'p@$swr0d44'                                                            
 Request failed: HTTPError: 503 Server Error: Service Unavailable for url: http://substra-backend.owkin.xyz:8000/api-token-auth/`

How can I solve this problem

**Comment by IcyLiGit** [comment]
I also install Substra in my MacBook. 
However, I met different problems:

```
substra login --profile owkin --username substra --password 'p@$swr0d44'

Error: Request failed: ConnectionError: HTTPConnectionPool(host='substra-backend.owkin.xyz', port=8000): Max retries exceeded with url: /api-token-auth/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109f80c88>: Failed to establish a new connection: [Errno 61] Connection refused',))
```

```
curl http://substra-backend.owkin.xyz:8000
curl: (7) Failed to connect to substra-backend.owkin.xyz port 8000: Connection refused
```

**Comment by natct10** [comment]
Hi and thank you for this feedback! The local installation with Docker is not the first recommendation, would you kindly try with the Kubernetes / Skaffold setup: https://doc.substra.ai/getting_started/installation/local_install_skaffold.html

**Comment by IcyLiGit** [comment]
@natct10  hi, I tried the k8s setup in the cloud machine. However, I also met the same problem.

`substra login --profile node-1 --username node-1 --password 'p@$swr0d44'
Max retries exceeded with url: /api-token-auth/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection   
`

How can I solve this problem. Many Thanks.

**Comment by jmorel** [comment]
Hello @IcyLiGit, this error occurs when you make more than X login calls in a given minute. You just need to wait a bit for it to disappear. The value of X depends on which value you set for the `DEFAULT_THROTTLE_RATES` environment variable. Default value when launching with skaffold is 120.

**Comment by RomainGoussault** [comment]
Closing this ticket as no new activity. @IcyLiGit feel free to reach out if you still have an isssue
