### ISSUE TITLE
Remove ghost git page

### ISSUE THREAD

**Issue by natct10** [Substra/substra#246]
I have been trying to remove an old test github page displayed on the substra repo but I don't have access to the "settings" so I can't go further:

![Screenshot_2020-11-18 SubstraFoundation substra](https://user-images.githubusercontent.com/44260056/99553828-de000380-29be-11eb-92b7-6208dc06febd.png)

This page is related to the now private & archived github.io repo, but I don't know how it ended on the substra repo, and delete the github page was not "easy": 

![Screenshot_2020-11-18 SubstraFoundation SubstraFoundation github io](https://user-images.githubusercontent.com/44260056/99553990-0687fd80-29bf-11eb-8836-e2fc66b46e54.png)

Could anyone with access to the settings of the substra repo edit this "deployment" section?
Otherwise do you have any idea where/how this is to be disabled?

**Comment by jmorel** [comment]
I don't have access to the settings either, @samlesu @ClementGautier @camillemarini I think one of you is an admin for the repo, could you handle it?

**Comment by ClementGautier** [comment]
Only an an admin can do it. I'm not one anymore, only @bowni @camillemarini and @inalgnu can.

**Comment by natct10** [comment]
Update: The github.io repo has been removed, so the url now returns a 404, but the "deployment" reference is still there...

**Comment by RomainGoussault** [comment]
@camillemarini could you please remove this Environnements section? Thanks!

**Comment by inalgnu** [comment]
@RomainGoussault it's done

**Comment by inalgnu** [comment]
Closing the issue
