### ISSUE TITLE
Would be nice to have an example that use data submitted to two nodes

### ISSUE THREAD

**Issue by camillemarini** [Substra/substra#25]
In the titanic example, data are submitted to one node only. It would be nice to have two scripts mimicking two actors that would add data in two nodes (two since in our local setup we use two nodes by default). This could be done in addition to the current example.
We could then in the compute plan example have an model that is created from data from two nodes.

**Comment by jmorel** [comment]
This would be a great addition to our examples!

**Comment by Esadruhn** [comment]
Closing as stale
