### ISSUE TITLE
Allow aggregatetuples as input models of traintuples in debug mode

### ISSUE THREAD

**Issue by Fabien-GELUS** [Substra/substra#262]
I tried to make a compute plan with traintuples and aggregate tuples. It failed in debug mode because the traintuples are looking for traintuple ids as inmodel ids, and not aggregatetuples.

We could change the check here:
https://github.com/SubstraFoundation/substra/blob/fc2d50f2f80be14c0c80546451cdf458034dbf78/substra/sdk/backends/local/backend.py#L541
In order to have the same rules as in substra backend:
https://github.com/SubstraFoundation/substra-backend/blob/7b3e494102084ddf7a260dbaf069ba414316426b/backend/substrapp/tasks/tasks.py#L137-L138

**Comment by Esadruhn** [comment]
Closing as stale
