### ISSUE TITLE
Trying to run Titanic example

### ISSUE THREAD

**Issue by Martiniann** [Substra/substra#270]
Hello, 

I wanted to try out your framework and I stumbled on this error: 
![substra connection error](https://user-images.githubusercontent.com/67962563/121921718-8d287180-cd39-11eb-8e93-bc57a4a0a4e4.png)

I was doing the exact same steps as in your Titanic tutorial. Do I need to run these commands inside docker container substra-tools that i pulled and built or what am I doing wrong? Some advice would be very appreciated, thanks.

**Comment by RomainGoussault** [comment]
Hello @Martiniann, the issue you have is that you are trying to connect to deployed Substra platform at `http://substra-backend.node-1.com` which does not exist. There are three solutions:
- Use an already deployed platform, you request access [here](https://doc.substra.ai/demo.html).
- Deploy the platform yourself, detailed instructions are [here](https://doc.substra.ai/setup/index.html). 
- Use the substra in debug mode, instructions [here](https://github.com/Substra/substra/tree/master/examples/debugging). In this mode everything run locally and you don't need a deployed platform.

I would recommend the last option to start, it is going to be the easiest

**Comment by Esadruhn** [comment]
Closing this issue as it is stale, do not hesitate to repoen it or create a new one if you have follow-up comments/questions
