### ISSUE TITLE
tests: run tests in subprocess

### ISSUE THREAD

**Issue by Fabien-GELUS** [Substra/substra#306]
The tests marked as "subprocess" don't actually run on subprocess but on docker

To reproduce:
close docker desktop / client
run `make test`

There are docker errors in the subprocess tests: 
`ERROR tests/sdk/local/test_debug.py::TestsDebug::test_tasks_extra_fields[subprocess] - ConnectionError: Couldn't get the Docker client from environment variables. `

**Comment by ThibaultFy** [comment]
As there is no "mark" in the substra tests, all fixtures are loaded, even the docker ones, that will trigger a ConnectionError even for some of the subprocess mode that are parametrize alongside docker mode.
