### ISSUE TITLE
ENH: Eval_Strategy round options should be mutually exclusive

### ISSUE THREAD

**Issue by tanguy-marchand** [Substra/substra#343]
### Feature Type

- [ ] Adding new functionality to Substra

- [X] Changing existing functionality in Substra

- [ ] Removing existing functionality in Substra

### Problem Description

The `EvaluationStrategy` constructor accepts the two following options:

```
eval_frequency: Optional[int] = 1,
eval_rounds: Optional[List[int]] = None,
```
It both are not None, the strategy is tested for the union of all the rounds concerned by the two options. This is a bit misleading as someone doing:
```
my_eval_strategy = EvaluationStrategy(
        test_data_nodes=test_data_nodes,
        eval_rounds=[1,5,7,10],
    )
```
does not expect to have the strategy evaluated as each single round. While this is the case actually as by default `eval_frequency` is set to 1.

Therefore today the user has to do:
```
my_eval_strategy = EvaluationStrategy(
        test_data_nodes=test_data_nodes,
        eval_frequency = None
        eval_rounds=[1,5,7,10],
    )
```

### Feature Description

I suggest to simplicity to:
- either discard eval_frequency when eval_rounds is not None
or
- (preferred solution) set both eval_frequency and eval_rounds to None by default, and raising an error if the user does not provide at least one of the argument.

### Additional Context

Notice that it's frequent to have mutually exclusive options in Python. Here are two examples from standard librairies:

- `dx` and `x` option in np.trapz https://numpy.org/doc/stable/reference/generated/numpy.trapz.html
- `range` and `bins` in plt.hist: https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.hist.html

**Comment by ThibaultFy** [comment]
Thanks @tanguy-marchand for launching this discussion. 
Now that you're pointing at the issue, I agree that it is not optimal. 
The idea of having the possibility to "join" the two value is to add a kind of a hybrid mode were you want to test a lot on the first rounds, and then on a larger frequency.

For instance:

`my_eval_strategy = EvaluationStrategy(
        test_data_nodes=test_data_nodes,
        eval_frequency = 5
        eval_rounds=[0,1,2,3,4],
    )`
    
    Regarding your solution, setting both to `None` y default would solve this issue.
    
   What's your opinion on this ? Do you think this hybrid mode would be an interesting feature to keep ?

**Comment by RomainGoussault** [comment]
Thanks for raising this @tanguy-marchand. This was designed this way to have a sensible default when you start. However I agree this lead to the the issue you mentioned above.

Regarding the solution I would go with defaulting both options to `None` and raise an error when at least one of them is no set.

**Comment by ThibaultFy** [comment]
Agree with this solution. The error is already dealt with, so the PR would be only changing the default value. I'll do the PR

**Comment by ThibaultFy** [comment]
In review : https://github.com/Substra/substrafl/pull/91
