### ISSUE TITLE
BUG: when calling client.list_task() the output type depends on the type of the backend

### ISSUE THREAD

**Issue by jeandut** [Substra/substra#354]
### What are you trying to do?

I am calling `client.list_task()` after having run compute plans using different backends.

### Issue Description (what is happening?)

I get different output types with different backend:
subprocess:
list[Task]
docker
list[Task]
remote
list[SummaryTask]

### Expected Behavior (what should happen?)

The remote backend should return a list of Tasks as well

### Operating system

MacOsX

### Python version

3.9.16

### Installed Substra versions

```python
substra==0.43.0
substrafl==0.35.1
-e git+https://github.com/Substra/substra-tools.git@ed471f633feaaed90c834c0aed65c2e2e6db55aa#egg=substratools
```

**Comment by SdgJlbl** [comment]
Thanks for the bug report ❤️ 
It's not a bug, it's working as "intended". 
The `SummaryTask`  type was introduced to solve some performance issues on the backend, and we had to introduce a matching type in Substra SDK. We are aware that the naming is not good, but we are in the process of refactoring that part, and it should revert to having only `Task` type in the SDK very soon 🙂
