### ISSUE TITLE
Local install using skaffold, on Windows

### ISSUE THREAD

**Issue by RomainGoussault** [Substra/substra#65]
Following this [guide](https://github.com/SubstraFoundation/substra/blob/master/docs/local_install_skaffold.md), I tried to install Substra locally on a Windows machine.

The issues I encounted were:
* helm must be installed before running the command `helm init` (I thought it might have been installed when installing Docker desktop)
* `helm init` has been removed from helm 3.0. Should I use helm 2.* or just don't run `helm init` ? 
* when defining alias: `sudo ifconfig lo0 alias 192.168.65.2`. I am not sure how to translate this command on Windows. Following this [link](https://superuser.com/questions/1270789/how-to-setup-ip-alias-to-local-network-on-windows), I am not sure which network name to use among the eight that I have.

**Comment by Kelvin-M** [comment]
We never tested the installation of Substra on a Windows.
Maybe you could start a PR for this and precise on which step you're blocked.

**Comment by natct10** [comment]
@RomainGoussault We can work on this together as well!

**Comment by jmorel** [comment]
@RomainGoussault @natct10 did you manage to make it work on windows?

**Comment by RomainGoussault** [comment]
Not yet. I am going to try again with the new [documentation](https://substrafoundation.github.io/substra-documentation/index.html).

**Comment by samlesu** [comment]
@RomainGoussault did you make any progress on this PR?

**Comment by RomainGoussault** [comment]
I did not try again to install a substra backend on my windows machine. 

However I tried the substra client on windows: the python SDK worked but the CLI did not work.

**Comment by RomainGoussault** [comment]
Hello Romain, we do not support installing (the server side of) substra on windows.
